### ISSUE TITLE
catkin make error

### ISSUE THREAD

**Issue by james2254** [ros-industrial-attic/godel#105] opened 2016-04-05 08:38 UTC
When I run catkin_make in the terminal ,there is a error

```
+++ processing catkin package: 'godel_openvoronoi'
-- ==> add_subdirectory(godel_openvoronoi/src)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   graph
CMake Error at godel_openvoronoi/src/Findqd.cmake:39 (MESSAGE):
  Could not find QD
Call Stack (most recent call first):
  godel_openvoronoi/src/CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/james/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/james/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```

what's happen? how can I correct it?

**Comment by gavanderhoorn** [comment] 2016-04-05 09:29
Did you follow the installation instructions in the [readme](https://github.com/ros-industrial-consortium/godel/blob/indigo-devel/README.md)?

The error you see is probably caused by a missing `libqd-dev` (needed by `godel_openvoronoi`), which the `rosdep install ..` step in the installation instructions installs for you.

**Comment by james2254** [comment] 2016-04-06 07:13
Thank you , it's correct follow the installation.

**Comment by phvass** [comment] 2017-01-13 16:08
Assuming this was just an installation issue... Closing.

**Closed as completed by phvass** 2017-01-13 16:08 UTC
